name: Open issue if Codespaces Prebuild fails
on:
  workflow_run:
    workflows:
      - Codespaces Prebuilds
    types:
      - completed

jobs:
  workflow-failure-issues:
    uses: urcomputeringpal/.github/.github/workflows/workflow-failure-issues.yaml@main
